---
Routers:
- Rewrite
- Static
- Regex
Hooks:
  beforeRoute:
    Remove Trailing Slashes:
      Service: Code.Routing.Hooks.RemoveTrailingSlashes
      Method: beforeRoute
    -Extension:
      Service: Code.Routing.Hooks.ParseExtension
      Method: beforeRoute
  afterRoute:
    -Extension:
      Service: Code.Routing.Hooks.ParseExtension
      Method: afterRoute
...
