---
Meta:
  Title:
    Delimiter: ' - '
    Reverse: true
  Pattern:
    Title: (<title/>)
    Keywords: (<keywords/>)
    Description: (<description/>)
  Sources:
    Title:
      Service: View.HTML.Meta.Scan
      Method: Title
    Keywords:
      Service: View.HTML.Meta.Scan
      Method: Keywords
    Description:
      Service: View.HTML.Meta.Scan
      Method: Description
...
