---
ID: Codeine
Title: My Project on Codeine
Join:
  Open: true
Description:
  Short: Short description goes here
  Full: Full description goes here
Hosts:
  Development: codeine.localhost
Currency: RUR
Audience:
  suggestedGender: ""
  suggestedMinAge: 18
  suggestedMaxAge: 49
  requiredMinAge: 18
  requiredMaxAge: 49
...
