---
Contract:
  Code.Flow.Application:
    Run:
      Memo:
      - Run.Service
      - Run.Method
      - Run.Call
      - Time
View:
  Renderer:
    Service: View.HTML
    Method: Render
Context: app
Run:
  Method: Do
Hooks:
  beforeApplicationRun:
    Layouts:
      Service: Code.Flow.Application.Layouts
      Method: Do
    Prepare:
      Service: Code.Flow.Front.Before
      Method: Do
    Access:
      Service: Code.Flow.Application.Access
      Method: Check
    Project:
      Service: Project.Preload
      Method: beforeFrontRun
      Must be first: true
  afterApplicationRun:
    Rendering:
      Service: View.HTML
      Method: Pipeline
  Access:
    Denied:
      ErrorBlock:
        Service: Error.Page
        Method: Catch
        Call:
          Code: 403
...
