---
Rules:
  Dev Theme / All:
    Decision: true
    Weight: 50
    Run:
      Service: Developer.Theme
      Method: Do
  Dev Translate / All:
    Decision: true
    Weight: 150
    Run:
      Service: Locale.Live
  Features / List:
    Decision: true
    Weight: 150
    Run:
      Service: Developer.Feature.List
...
