---
Rules:
  List photo allowed to all:
    Decision: true
    Weight: 50
    Run:
      Service: Entity.List
      Method: Do
      Call:
        Entity: Photo
  Show photo allowed to all:
    Decision: true
    Weight: 50
    Run:
      Service: Entity.Show.Static
      Method: Do
      Call:
        Entity: Photo
...
